//! Use-case: register an app and mint its Contract.

use std::sync::Arc;
use vault_domain::{AppContract, ErasureParams, Quota, RetentionPolicy};
use vault_ports::{IdSource, MetadataStore, PortResult};

pub struct RegisterApp {
    metadata: Arc<dyn MetadataStore>,
    ids: Arc<dyn IdSource>,
}

impl RegisterApp {
    pub fn new(metadata: Arc<dyn MetadataStore>, ids: Arc<dyn IdSource>) -> Self {
        Self { metadata, ids }
    }

    /// Onboard an app: allocate an opaque `AppId`, build the Contract, persist
    /// it, and return the Contract. The app signing keypair is generated by the
    /// caller (coordinator) and is not part of domain policy.
    pub async fn execute(
        &self,
        quota: Quota,
        retention: RetentionPolicy,
        erasure: ErasureParams,
    ) -> PortResult<AppContract> {
        let app_id = self.ids.new_id("app").into();
        let contract = AppContract::new(app_id, quota, retention, erasure);
        self.metadata.register_app(&contract).await?;
        Ok(contract)
    }
}
